// teamLogos.ts
export const teamLogos: Record<string, string> = {
    "Ducks": "https://assets.nhle.com/logos/nhl/svg/ANA_light.svg",
    "Coyotes": "https://assets.nhle.com/logos/nhl/svg/CGY_light.svg",
    "Bruins": "https://assets.nhle.com/logos/nhl/svg/BOS_light.svg",
    "Sabres": "https://assets.nhle.com/logos/nhl/svg/BUF_light.svg",
    "Flames": "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg",
    "Hurricanes": "https://assets.nhle.com/logos/nhl/svg/CAR_light.svg",
    "Blackhawks": "https://assets.nhle.com/logos/nhl/svg/CHI_light.svg",
    "Avalanche": "https://assets.nhle.com/logos/nhl/svg/COL_light.svg",
    "Blue Jackets": "https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg",
    "Stars": "https://assets.nhle.com/logos/nhl/svg/DAL_light.svg",
    "Red Wings": "https://assets.nhle.com/logos/nhl/svg/DET_light.svg",
    "Oilers": "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
    "Panthers": "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg",
    "Kings": "https://assets.nhle.com/logos/nhl/svg/LAK_light.svg",
    "Wild": "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg",
    "Canadiens": "https://assets.nhle.com/logos/nhl/svg/MTL_light.svg",
    "Predators": "https://assets.nhle.com/logos/nhl/svg/NSH_light.svg",
    "Devils": "https://assets.nhle.com/logos/nhl/svg/NJD_light.svg",
    "Islanders": "https://assets.nhle.com/logos/nhl/svg/NYI_light.svg",
    "Rangers": "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg",
    "Senators": "https://assets.nhle.com/logos/nhl/svg/OTT_light.svg",
    "Flyers": "https://assets.nhle.com/logos/nhl/svg/PHI_light.svg",
    "Penguins": "https://assets.nhle.com/logos/nhl/svg/PIT_light.svg",
    "Sharks": "https://assets.nhle.com/logos/nhl/svg/SJS_light.svg",
    "Kraken": "https://assets.nhle.com/logos/nhl/svg/SEA_light.svg",
    "Blues": "https://assets.nhle.com/logos/nhl/svg/STL_light.svg",
    "Lightning": "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg",
    "Maple Leafs": "https://assets.nhle.com/logos/nhl/svg/TOR_light.svg",
    "Canucks": "https://assets.nhle.com/logos/nhl/svg/VAN_light.svg",
    "Golden Knights": "https://assets.nhle.com/logos/nhl/svg/VGK_light.svg",
    "Capitals": "https://assets.nhle.com/logos/nhl/svg/WSH_light.svg",
    "Jets": "https://assets.nhle.com/logos/nhl/svg/WPG_light.svg",
    "Utah Hockey Club": "/Utah.png",
  }
  